export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const ADD_TO_COUNTER = 'ADD_TO_COUNTER';
export const SUBTRACT_FROM_COUNTER = 'SUBTRACT_FROM_COUNTER';
export const STORE_RESULT = 'STORE_RESULT';
export const DELETE_RESULT = 'DELETE_RESULT';